# Generated by Django 4.2.2 on 2024-04-17 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_application', models.DateTimeField(verbose_name='date_application')),
                ('telegram_id', models.IntegerField(verbose_name='telegram_id')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone_number')),
                ('first_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='last_name')),
                ('date_joined', models.DateTimeField(verbose_name='date_joined')),
                ('catalog_id', models.IntegerField(verbose_name='catalog_id')),
                ('category_id', models.IntegerField(verbose_name='category_id')),
                ('category', models.CharField(max_length=128, verbose_name='category_title')),
                ('catalog_title', models.CharField(max_length=255, verbose_name='catalog_title')),
                ('details', models.TextField(blank=True, null=True, verbose_name='catalog_details')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='catalog_price')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='photo')),
                ('final', models.TextField(blank=True, null=True, verbose_name='final')),
            ],
            options={
                'db_table': 'view_application',
                'ordering': ['date_application'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(verbose_name='category_id')),
                ('category', models.CharField(max_length=128, verbose_name='category_title')),
                ('catalog_title', models.CharField(max_length=255, verbose_name='catalog_title')),
                ('details', models.TextField(blank=True, null=True, verbose_name='catalog_details')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='catalog_price')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='photo')),
            ],
            options={
                'db_table': 'view_catalog',
                'ordering': ['category', 'catalog_title'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=128, unique=True, verbose_name='category_title')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(unique=True, verbose_name='telegram_id')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone_number')),
                ('first_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='last_name')),
                ('date_joined', models.DateTimeField(verbose_name='date_joined')),
            ],
            options={
                'db_table': 'customer',
                'ordering': ['first_name', 'last_name'],
                'indexes': [models.Index(fields=['telegram_id'], name='customer_telegra_f5e35d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_title', models.CharField(max_length=255, verbose_name='catalog_title')),
                ('details', models.TextField(blank=True, null=True, verbose_name='catalog_details')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='catalog_price')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='catalog_photo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_category', to='product.category')),
            ],
            options={
                'db_table': 'catalog',
                'ordering': ['catalog_title'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_application', models.DateTimeField(auto_now_add=True, verbose_name='date_application')),
                ('telegram_id', models.IntegerField(verbose_name='telegram_id')),
                ('catalog', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='application_catalog', to='product.catalog')),
            ],
            options={
                'db_table': 'application',
                'ordering': ['date_application'],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datem', models.DateTimeField(verbose_name='datem')),
                ('status', models.CharField(max_length=128, verbose_name='movement_status')),
                ('details', models.TextField(blank=True, null=True, verbose_name='movement_details')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_application', to='product.application')),
            ],
            options={
                'db_table': 'movement',
                'ordering': ['datem'],
                'indexes': [models.Index(fields=['application'], name='movement_applica_27871b_idx'), models.Index(fields=['datem'], name='movement_datem_8708fe_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='catalog',
            index=models.Index(fields=['catalog_title'], name='catalog_catalog_d497ec_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['date_application', 'telegram_id'], name='application_date_ap_0a82d5_idx'),
        ),
    ]
