# Generated by Django 4.2.2 on 2024-04-14 04:26

from pickle import FALSE, TRUE
from django.contrib.auth.models import User
from django.contrib.auth.models import Group

from django.db import migrations
# Подключаем модуль для работы с датой/веременем
from datetime import datetime, timedelta
# Подключаем модкль генерации случайных чисел
import random

# Получение случайного ID телеграмм 9 цифр (например 611996998)
def get_telegram_id():
    telegram_id = ""
    for n in range(9):
        telegram_id = telegram_id + str(random.randint(0, 9)) 
    return telegram_id

# Получение случайного телефона
def get_telefon():
    if random.randint(0, 1) == 1:
        telefon = "+7-701-"
    else:
        telefon = "+7-705-" 
    telefon = telefon + str(random.randint(0, 9)) + str(random.randint(0, 9)) + str(random.randint(0, 9)) + "-" + str(random.randint(0, 9)) + str(random.randint(0, 9)) + str(random.randint(0, 9)) + str(random.randint(0, 9)) 
    return telefon

# Найти или Добавить Категорию
global dict_category
dict_category = {}

def get_category(apps, val):   
    # Поиск категории
    if val in dict_category.values():
        for k, v in dict_category.items():
            if v == val:
                return k    
    else:
        Category = apps.get_model("product", "Category")
        category = Category()
        category.category_title = val
        category.save()
        dict_category[category.id] = category.category_title
        return category.id

# Добавить товар 
def insert_catalog(apps, param_catalog):   
    Catalog = apps.get_model("product", "Catalog")
    catalog = Catalog()
    catalog.category_id = param_catalog[0]
    catalog.catalog_title = param_catalog[1]
    catalog.details = param_catalog[2]
    catalog.price = param_catalog[3]
    catalog.photo = param_catalog[4]
    catalog.save()
    return

# Добавить Пользователи Telegram 
def insert_customer(apps, param):   
    Customer = apps.get_model("product", "Customer")
    customer = Customer()
    customer.telegram_id = param[0]
    customer.phone_number = param[1]
    customer.first_name = param[2]
    customer.last_name = param[3]
    customer.date_joined = param[4]
    customer.save()
    return

# Добавить Заявку 
def insert_application(apps, param):   
    Application = apps.get_model("product", "Application")
    application = Application()
    application.date_application = param[0]
    application.telegram_id = param[1]
    application.catalog_id = param[2]
    application.save()
    application.date_application = param[0]
    application.save()
    # Добавить движенеи заявки
    parameters = [application.id, application.date_application, "Заявка принята", "Заявка принята в обработку"]
    insert_movement(apps, parameters)
    parameters = [application.id, application.date_application + timedelta(days=1), "Заявка в работе", "Заявка в работе"]
    insert_movement(apps, parameters)
    return

# Добавить движение заявки клиента 
def insert_movement(apps, param_movement):   
    Movement = apps.get_model("product", "Movement")
    movement = Movement()
    movement.application_id = param_movement[0]
    movement.datem = param_movement[1]
    movement.status = param_movement[2]
    movement.details = param_movement[3]
    movement.save()
    movement.datem = param_movement[1]
    movement.save()
    return


# Начальные данные 
def new_data(apps, schema_editor):
    try:
        # Суперпользователь id=1
        user = User.objects.create_superuser(username='root',
        email='shop140424@mail.ru',
        first_name='Марат', 
        last_name='Баядилов',
        password='SsNn5678+-@')
        print("Суперпользователь создан")
    
        # Группа менеджеров
        managers = Group.objects.get_or_create(name = 'Managers')
        managers = Group.objects.get(name='Managers')
        print("Группа менеджеров создана")
    
        # Пользователь с ролью менеджера id=2
        user = User.objects.create_user(username='manager', password='Ss0066+-', email='manager@mail.ru', first_name='Алмат', last_name='Кужахметов')
        managers.user_set.add(user)
        print("Менеджер добавлен в группу менеджеров")

        #1 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Samsung"), "Samsung Galaxy A25 5G, 128 GB (SM-A256E)", """Размер экрана, дюйм: 6.5
Разрешение экрана: 2340 x 1080 [19.5:9]
Тип матрицы: Super AMOLED
Объем оперативной памяти: 6 ГБ
Объем встроенной памяти: 128 ГБ
Модель процессора: Exynos 1280
Частота процессора: 2.4 ГГц + 2.0 ГГц
Основная камера, Мп: 50 + 8 + 2
Фронтальная камера, Мп: 13
Беспроводные интерфейсы: Wi-Fi, Bluetooth, NFC
Емкость аккумулятора: 5000 мАч""", 119990, "images/catalog01.jpg"]		
        insert_catalog(apps, parameters)   
        
        parameters = [get_category(apps, "Samsung"), "Samsung Galaxy A05, 64 GB (SM-A055F)", """Размер экрана, дюйм: 6.7
Разрешение экрана: 1600 x 720 [20:9]
Тип матрицы: PLS
Объем оперативной памяти: 4 ГБ
Объем встроенной памяти: 64 ГБ
Модель процессора: Helio G85
Частота процессора: 1.8 ГГц + 2 ГГц
Основная камера, Мп: 50 + 2
Фронтальная камера, Мп: 8
Беспроводные интерфейсы: Wi-Fi, Bluetooth
Емкость аккумулятора: 5000 мАч""", 54890, "images/catalog02.jpg"]		
        insert_catalog(apps, parameters)   
        
        parameters = [get_category(apps, "Xiaomi"), "Redmi A3, 128 GB (23129RN51X)", """Размер экрана, дюйм: 6.71
Разрешение экрана: 1650 x 720 [20.6:9]
Объем оперативной памяти: 4 ГБ
Объем встроенной памяти: 128 ГБ
Модель процессора: Helio G36
Частота процессора: 2.2 ГГц
Основная камера, Мп: 8
Фронтальная камера, Мп: 5
Беспроводные интерфейсы: Wi-Fi, Bluetooth
Емкость аккумулятора: 5000 мАч""", 45990, "images/catalog03.jpg"]		
        insert_catalog(apps, parameters)   
        
        parameters = [get_category(apps, "Samsung"), "Samsung Galaxy A15, 128 GB (SM-A155F)", """Размер экрана, дюйм: 6.5
Разрешение экрана: 2340 x 1080 [19.5:9]
Тип матрицы: Super AMOLED
Объем оперативной памяти: 6 ГБ
Объем встроенной памяти: 128 ГБ
Модель процессора: Helio G99
Частота процессора: 2 ГГц
Основная камера, Мп: 50 + 5 + 2
Фронтальная камера, Мп: 13
Беспроводные интерфейсы: Wi-Fi, Bluetooth, NFC
Емкость аккумулятора: 5000 мАч""", 86990, "images/catalog04.jpg"]		
        insert_catalog(apps, parameters)   
        
        parameters = [get_category(apps, "Xiaomi"), "Xiaomi 14, 512 GB (23127PN0CG)", """Размер экрана, дюйм: 6.36
Разрешение экрана: 2670 x 1200
Тип матрицы: AMOLED, LTPO
Объем оперативной памяти: 12 ГБ
Объем встроенной памяти: 512 ГБ
Модель процессора: Snapdragon 8 Gen 3
Частота процессора: 3.3 ГГц
Основная камера, Мп: 50 + 50 + 50
Фронтальная камера, Мп: 32
Беспроводные интерфейсы: Wi-Fi, Bluetooth, NFC
Емкость аккумулятора: 4610 мАч""", 549990, "images/catalog05.jpg"]		
        insert_catalog(apps, parameters)   
        
        parameters = [get_category(apps, "Xiaomi"), "Redmi Note 13 Pro, 256 GB, (23117RA68G)", """Размер экрана, дюйм: 6.55
Размер экрана, дюйм: 6.67
Разрешение экрана: 2400 x 1080 [20:9]
Тип матрицы: AMOLED
Объем оперативной памяти: 8 ГБ
Объем встроенной памяти: 256 ГБ
Модель процессора: Helio G99
Частота процессора: 2.2 ГГц
Основная камера, Мп: 200 + 8 + 2
Фронтальная камера, Мп: 16
Беспроводные интерфейсы: Wi-Fi, Bluetooth, NFC, IrDA
Емкость аккумулятора: 5000 мАч""", 149900, "images/catalog06.jpg"]		
        insert_catalog(apps, parameters)   
        
        parameters = [get_category(apps, "Tecno "), "Tecno Camon 12 Air, 32Gb, (CC6)", """Размер экрана, дюйм: 6.55
Разрешение экрана: 1600 x 720 [20:9]
Тип матрицы: IPS
Объем оперативной памяти: 3 ГБ
Объем встроенной памяти: 32 ГБ
Модель процессора: Helio A22
Частота процессора: 2.0 ГГц
Фронтальная камера, Мп: 8
Беспроводные интерфейсы: Wi-Fi, Bluetooth
Емкость аккумулятора: 4000 мАч""", 59990, "images/catalog07.jpg"]		
        insert_catalog(apps, parameters)   
        
        parameters = [get_category(apps, "Tecno"), "Tecno Spark 9 Pro, 128 GB, (KH7n)", """Размер экрана, дюйм: 6.6
Разрешение экрана: 2408 x 1080
Объем оперативной памяти: 4 ГБ
Объем встроенной памяти: 128 ГБ
Модель процессора: Helio G85
Частота процессора: 2.0 ГГц + 1.8 ГГц
Основная камера, Мп: 50 + 2 + 0.08
Фронтальная камера, Мп: 32
Беспроводные интерфейсы: Wi-Fi, Bluetooth, NFC
Емкость аккумулятора: 5000 мАч""", 68690, "images/catalog08.jpg"]		
        insert_catalog(apps, parameters)   
        
        parameters = [get_category(apps, "POCO"), "POCO M6 Pro, 512 GB,(2312FPCA6G)", """Размер экрана, дюйм: 6.67
Разрешение экрана: 2400 x 1080 [20:9]
Тип матрицы: Flow AMOLED
Объем оперативной памяти: 12 ГБ
Объем встроенной памяти: 512 ГБ
Модель процессора: Helio G99-Ultra
Частота процессора: 2.2 ГГц + 2.0 ГГц
Основная камера, Мп: 64 + 8 + 2
Фронтальная камера, Мп: 16
Беспроводные интерфейсы: Wi-Fi, Bluetooth, NFC, IrDA
Емкость аккумулятора: 5000 мАч""", 116990, "images/catalog09.jpg"]		
        insert_catalog(apps, parameters)   

        parameters = [get_category(apps, "Tecno"), "Tecno Phantom V Flip, 256 GB, (AD11)", """Размер экрана, дюйм: 6.9
Разрешение экрана: 2640 x 1080
Тип матрицы: AMOLED
Объем оперативной памяти: 8 ГБ
Объем встроенной памяти: 256 ГБ
Модель процессора: Dimensity 8050
Частота процессора: 3 ГГц
Основная камера, Мп: 64 + 13
Фронтальная камера, Мп: 32
Беспроводные интерфейсы: Wi-Fi, Bluetooth, NFC
Емкость аккумулятора: 4000 мАч""", 449990, "images/catalog10.jpg"]		
        insert_catalog(apps, parameters)   

        parameters = [get_category(apps, "Tecno"), "Tecno Spark 20, 256 GB, (KJ5N)", """Размер экрана, дюйм: 6.56
Разрешение экрана: 1612 x 720 [20.1:9]
Тип матрицы: IPS
Объем оперативной памяти: 8 ГБ
Объем встроенной памяти: 256 ГБ
Модель процессора: G85
Частота процессора: 2 ГГц
Основная камера, Мп: 50 + 0.8
Фронтальная камера, Мп: 32
Беспроводные интерфейсы: Wi-Fi, Bluetooth, NFC
Емкость аккумулятора: 5000 мАч""", 89990, "images/catalog11.jpg"]		
        insert_catalog(apps, parameters)   

        parameters = [get_category(apps, "Tecno"), "Tecno Pova 5 Pro 5G, 256 GB, (LH8n)", """Размер экрана, дюйм: 6.78
Разрешение экрана: 2460 x 1080
Объем оперативной памяти: 8 ГБ
Объем встроенной памяти: 256 ГБ
Модель процессора: Dimensity 6080
Частота процессора: 2.4 ГГц
Основная камера, Мп: 50 + Al
Фронтальная камера, Мп: 16
Беспроводные интерфейсы: Wi-Fi, Bluetooth, NFC
Емкость аккумулятора: 5000 мАч""", 119990, "images/catalog12.jpg"]		
        insert_catalog(apps, parameters)   

        parameters = [get_category(apps, "Tecno"), "Tecno Camon 20 Pro, 256 GB, (CK7n)", """Размер экрана, дюйм: 6.7
Разрешение экрана: 2400 x 1080 [20:9]
Тип матрицы: AMOLED
Объем оперативной памяти: 8 ГБ
Объем встроенной памяти: 256 ГБ
Модель процессора: Helio G99
Частота процессора: 2.2 ГГц
Основная камера, Мп: 64 + 8 + 2
Фронтальная камера, Мп: 32
Беспроводные интерфейсы: Wi-Fi, Bluetooth, NFC
Емкость аккумулятора: 5000 мАч""", 109990, "images/catalog13.jpg"]		
        insert_catalog(apps, parameters)   

        parameters = [get_category(apps, "motorola"), "motorola razr 40, 256 GB, (PAYA0016TN)", """Размер экрана, дюйм: 6.9
Разрешение экрана: 2640 x 1080
Тип матрицы: AMOLED, LTPO
Объем оперативной памяти: 8 ГБ
Объем встроенной памяти: 256 ГБ
Модель процессора: Snapdragon 7 Gen 1
Частота процессора: 2.4 ГГц
Основная камера, Мп: 64 + 13
Фронтальная камера, Мп: 32
Беспроводные интерфейсы: Wi-Fi, Bluetooth, NFC
Емкость аккумулятора: 4200 мАч""", 299990, "images/catalog14.jpg"]		
        insert_catalog(apps, parameters)   

        parameters = [get_category(apps, "motorola"), "motorola moto g54 5G, 256 GB, (PAYT0035TN)", """Размер экрана, дюйм: 6.5
Разрешение экрана: 2400 x 1080 [20:9]
Объем оперативной памяти: 8 ГБ
Объем встроенной памяти: 256 ГБ
Модель процессора: Dimensity 7020
Частота процессора: 2.2 ГГц
Основная камера, Мп: 50 + 2
Фронтальная камера, Мп: 16
Беспроводные интерфейсы: Wi-Fi, Bluetooth, NFC
Емкость аккумулятора: 5000 мАч""", 99990 , "images/catalog15.jpg"]		
        insert_catalog(apps, parameters)   

        parameters = [get_category(apps, "motorola"), "motorola moto g84 5G, (PAYM0013TN)", """Размер экрана, дюйм: 6.5
Разрешение экрана: 2400 x 1080 [20:9]
Тип матрицы: POLED
Объем оперативной памяти: 12 ГБ
Объем встроенной памяти: 256 ГБ
Модель процессора: Snapdragon 695 5G
Частота процессора: 2.2 ГГц
Основная камера, Мп: 50 + 8
Фронтальная камера, Мп: 16
Беспроводные интерфейсы: Wi-Fi, Bluetooth, NFC
Емкость аккумулятора: 5000 мАч""", 129990, "images/catalog16.jpg"]		
        insert_catalog(apps, parameters)   

        parameters = [get_category(apps, "motorola"), "motorola moto e13, 64 GB, (PAXR0003TN)", """Размер экрана, дюйм: 6.5
Разрешение экрана: 1600 x 720 [20:9]
Тип матрицы: IPS
Объем оперативной памяти: 2 ГБ
Объем встроенной памяти: 64 ГБ
Модель процессора: T606
Частота процессора: 1.6 ГГц
Основная камера, Мп: 13
Фронтальная камера, Мп: 5
Беспроводные интерфейсы: Wi-Fi, Bluetooth
Емкость аккумулятора: 5000 мАч""", 34990, "images/catalog17.jpg"]		
        insert_catalog(apps, parameters)   

        parameters = [get_category(apps, "Xiaomi"), "Redmi 13C, 256 GB, (23106RN0DA)", """Размер экрана, дюйм: 6.74
Разрешение экрана: 1600 x 720 [20:9]
Объем оперативной памяти: 8 ГБ
Объем встроенной памяти: 256 ГБ
Модель процессора: Helio G85
Частота процессора: 2.0 ГГц + 1.8 ГГц
Основная камера, Мп: 50 + 2 + Al
Фронтальная камера, Мп: 8
Беспроводные интерфейсы: Wi-Fi, Bluetooth
Емкость аккумулятора: 5000 мАч""", 69990 , "images/catalog18.jpg"]		
        insert_catalog(apps, parameters)   

        parameters = [get_category(apps, "Samsung"), "Samsung Galaxy S23, 256 GB, (SM-S911B)", """Размер экрана, дюйм: 6.1
Разрешение экрана: 2340 x 1080 [19.5:9]
Тип матрицы: Dynamic AMOLED 2X
Объем оперативной памяти: 8 ГБ
Объем встроенной памяти: 256 ГБ
Модель процессора: Snapdragon 8 Gen 2
Частота процессора: 3.36 ГГц + 2.8 ГГц + 2 ГГц
Основная камера, Мп: 50 + 10 + 12
Фронтальная камера, Мп: 12
Беспроводные интерфейсы: Wi-Fi, Bluetooth, NFC
Емкость аккумулятора: 3900 мАч""", 364890, "images/catalog19.jpg"]		
        insert_catalog(apps, parameters)   

        parameters = [get_category(apps, "Samsung"), "Samsung Galaxy Z Fold5, 256 GB, (SM-F946B)", """Размер экрана, дюйм: 7.6
Разрешение экрана: 2160 x 1812
Тип матрицы: Dynamic AMOLED 2X
Объем оперативной памяти: 12 ГБ
Объем встроенной памяти: 256 ГБ
Модель процессора: Snapdragon 8 Gen 2
Частота процессора: 3.36 ГГц + 2.8 ГГц + 2 ГГц
Основная камера, Мп: 50 + 10 + 12
Фронтальная камера, Мп: 4
Беспроводные интерфейсы: Wi-Fi, Bluetooth, NFC
Емкость аккумулятора: 4400 мАч""", 799990, "images/catalog20.jpg"]		
        insert_catalog(apps, parameters)   

        parameters = [get_category(apps, "POCO"), "POCO C65, 256 GB, (2310FPCA4G)", """Размер экрана, дюйм: 6.74
Разрешение экрана: 1600 x 720 [20:9]
Объем оперативной памяти: 8 ГБ
Объем встроенной памяти: 256 ГБ
Модель процессора: Helio G85
Частота процессора: 2.0 ГГц + 1.8 ГГц
Основная камера, Мп: 50 + 2 + Al
Фронтальная камера, Мп: 8
Беспроводные интерфейсы: Wi-Fi, Bluetooth, NFC
Емкость аккумулятора: 5000 мАч""", 59990, "images/catalog21.jpg"]		
        insert_catalog(apps, parameters)   
        
        parameters = [get_category(apps, "Samsung"), "Samsung Galaxy Z Flip5, 512 GB, (SM-F731B)", """Размер экрана, дюйм: 6.7
Разрешение экрана: 2640 x 1080
Тип матрицы: Dynamic AMOLED 2X
Объем оперативной памяти: 8 ГБ
Объем встроенной памяти: 512 ГБ
Модель процессора: Snapdragon 8 Gen 2
Частота процессора: 3.36 ГГц + 2.8 ГГц + 2 ГГц
Основная камера, Мп: 12 + 12
Фронтальная камера, Мп: 10
Беспроводные интерфейсы: Wi-Fi, Bluetooth, NFC
Емкость аккумулятора: 3700 мАч""", 479890, "images/catalog22.jpg"]		
        insert_catalog(apps, parameters)   
        
        parameters = [get_category(apps, "motorola"), "motorola moto g32, 128 GB, (PAUV0010TN)", """Размер экрана, дюйм: 6.5
Разрешение экрана: 2400 x 1080 [20:9]
Объем оперативной памяти: 6 ГБ
Объем встроенной памяти: 128 ГБ
Модель процессора: Snapdragon 680
Частота процессора: 2.4 ГГц
Основная камера, Мп: 50 + 8 + 2
Фронтальная камера, Мп: 16
Беспроводные интерфейсы: Wi-Fi, Bluetooth, NFC
Емкость аккумулятора: 5000 мАч""", 74990, "images/catalog23.jpg"]		
        insert_catalog(apps, parameters)   
        
        parameters = [get_category(apps, "vivo"), "vivo V21, 128Gb, (V2066)", """Размер экрана, дюйм: 6.44
Разрешение экрана: 2404 x 1080 [20:9]
Тип матрицы: AMOLED
Объем оперативной памяти: 8 ГБ
Объем встроенной памяти: 128 ГБ
Модель процессора: Dimensity 800U
Частота процессора: 2.4 ГГц
Основная камера, Мп: 64 + 8 + 2
Фронтальная камера, Мп: 44
Беспроводные интерфейсы: Wi-Fi, Bluetooth, NFC
Емкость аккумулятора: 4000 мАч""", 139990, "images/catalog24.jpg"]		
        insert_catalog(apps, parameters)   
        
        parameters = [get_category(apps, "Xiaomi"), "Redmi A2+, 64 GB, (23028RNCAG)", """Размер экрана, дюйм: 6.52
Разрешение экрана: 1600 x 720 [20:9]
Объем оперативной памяти: 3 ГБ
Объем встроенной памяти: 64 ГБ
Модель процессора: Helio G36
Частота процессора: 2.2 ГГц
Основная камера, Мп: 8 + AI
Фронтальная камера, Мп: 5
Беспроводные интерфейсы: Wi-Fi, Bluetooth
Емкость аккумулятора: 5000 мАч""", 39990, "images/catalog25.jpg"]		
        insert_catalog(apps, parameters)   
        
        parameters = [get_category(apps, "Xiaomi"), "Redmi Note 12, 8 GB, 256 GB, (23021RAA2Y)", """Размер экрана, дюйм: 6.67
Разрешение экрана: 2400 x 1080 [20:9]
Тип матрицы: AMOLED
Объем оперативной памяти: 8 ГБ
Объем встроенной памяти: 256 ГБ
Модель процессора: Snapdragon 685
Частота процессора: 2.8 ГГц
Основная камера, Мп: 50 + 8 + 2
Фронтальная камера, Мп: 13
Беспроводные интерфейсы: Wi-Fi, Bluetooth, NFC, IrDA
Емкость аккумулятора: 5000 мАч""", 89990, "images/catalog26.jpg"]		
        insert_catalog(apps, parameters)   
        
        parameters = [get_category(apps, "motorola"), "motorola edge 30 Ultra, 256 GB, (PAUR0011TN)", """Размер экрана, дюйм: 6.67
Разрешение экрана: 2400 x 1080 [20:9]
Тип матрицы: POLED
Объем оперативной памяти: 12 ГБ
Объем встроенной памяти: 256 ГБ
Модель процессора: Snapdragon 8 Plus Gen 1
Частота процессора: 3.2 ГГц + 2.75 ГГц + 2 ГГц
Основная камера, Мп: 200 + 50 + 12
Фронтальная камера, Мп: 60
Беспроводные интерфейсы: Wi-Fi, Bluetooth, NFC
Емкость аккумулятора: 4610 мАч""", 339990, "images/catalog27.jpg"]		
        insert_catalog(apps, parameters)   
        
        parameters = [get_category(apps, "Xiaomi"), "Redmi Note 12S, 256 GB, (2303CRA44A)", """Размер экрана, дюйм: 6.43
Разрешение экрана: 2400 x 1080 [20:9]
Тип матрицы: AMOLED
Объем оперативной памяти: 8 ГБ
Объем встроенной памяти: 256 ГБ
Модель процессора: Helio G96
Частота процессора: 2.05 ГГц + 2.0 ГГц
Основная камера, Мп: 108 + 8 + 2
Фронтальная камера, Мп: 16
Беспроводные интерфейсы: Wi-Fi, Bluetooth, IrDA
Емкость аккумулятора: 5000 мАч""", 94990, "images/catalog28.jpg"]		
        insert_catalog(apps, parameters)   
        
        parameters = [get_category(apps, "realme"), "realme C30s, 64 GB, (RMX3690)", """Размер экрана, дюйм: 6.5
Разрешение экрана: 1600 x 720 [20:9]
Объем оперативной памяти: 4 ГБ
Объем встроенной памяти: 64 ГБ
Модель процессора: SC9863A
Частота процессора: 1.6 ГГц
Основная камера, Мп: 8
Фронтальная камера, Мп: 5
Беспроводные интерфейсы: Wi-Fi, Bluetooth
Емкость аккумулятора: 5000 мАч""", 39990, "images/catalog29.jpg"]		
        insert_catalog(apps, parameters)   
        
        parameters = [get_category(apps, "realme"), "realme C33, 64 GB, (RMX3624)", """Размер экрана, дюйм: 6.5
Разрешение экрана: 1600 x 720 [20:9]
Тип матрицы: IPS
Объем оперативной памяти: 4 ГБ
Объем встроенной памяти: 64 ГБ
Модель процессора: Tiger T612 (UMS9230)
Частота процессора: 1.8 ГГц
Основная камера, Мп: 50
Фронтальная камера, Мп: 5
Беспроводные интерфейсы: Wi-Fi, Bluetooth
Емкость аккумулятора: 5000 мАч""", 49990, "images/catalog30.jpg"]		
        insert_catalog(apps, parameters)   
        
        print("Каталог ОК")

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=90) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Меруерт", "Жансейтова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 1]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=85) + timedelta(minutes=random.randint(2, 360))
        parameters = [tel_id ,  get_telefon(), "Айнаш", "Тезекбаева", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 3]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=83) + timedelta(minutes=random.randint(2, 360))
        parameters = [tel_id ,  get_telefon(), "Максат", "Абиев", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 3]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=80) + timedelta(minutes=random.randint(2, 360))
        parameters = [tel_id ,  get_telefon(), "Алмагуль", "Сарманова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 5]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=75) + timedelta(minutes=random.randint(2, 360))
        parameters = [tel_id ,  get_telefon(), "Нұрсұлтан", "Қуанышбай", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 7]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=70) + timedelta(minutes=random.randint(2, 360))
        parameters = [tel_id ,  get_telefon(), "Жанболат", "Мансур", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 9]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=65) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Элмира", "Ермахан", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 11]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=63) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Индира", "Акимова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 11]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=61) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Арайлым", "Раушан", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 11]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=60) + timedelta(minutes=random.randint(2, 360))
        parameters = [tel_id ,  get_telefon(), "Арай", "Сындар", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 13]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=57) + timedelta(minutes=random.randint(2, 360))
        parameters = [tel_id ,  get_telefon(), "Данагуль", "Муканова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 13]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=55) + timedelta(minutes=random.randint(2, 360))
        parameters = [tel_id ,  get_telefon(), "Лаура", "Сейтханова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 15]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=53) + timedelta(minutes=random.randint(2, 360))
        parameters = [tel_id ,  get_telefon(), "Дария", "Дамирова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 15]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=50) + timedelta(minutes=random.randint(2, 360))
        parameters = [tel_id ,  get_telefon(), "Айдана", "Қаратай", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 17]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=48) + timedelta(minutes=random.randint(2, 360))
        parameters = [tel_id ,  get_telefon(), "Гавхар", "Махбубекова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 17]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=45) + timedelta(minutes=random.randint(2, 360))
        parameters = [tel_id ,  get_telefon(), "Арман", "Бейбіт", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 19]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=43) + timedelta(minutes=random.randint(2, 360))
        parameters = [tel_id ,  get_telefon(), "Айгерим", "Абдикаримова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 19]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=40) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Ержан", "Сулейменов", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 21]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=35) + timedelta(minutes=random.randint(2, 360))
        parameters = [tel_id ,  get_telefon(), "Динара", "Жолдасбаева", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 23]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=33) + timedelta(minutes=random.randint(2, 360))
        parameters = [tel_id ,  get_telefon(), "Лаура", "Әйтелбай", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 23]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=30) + timedelta(minutes=random.randint(2, 360))
        parameters = [tel_id ,  get_telefon(), "Айзада", "Асхатова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 25]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=25) + timedelta(minutes=random.randint(2, 360))
        parameters = [tel_id ,  get_telefon(), "Диана", "Абдыгалиева", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 27]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=20) + timedelta(minutes=random.randint(2, 360))
        parameters = [tel_id ,  get_telefon(), "Дамир", "Тагамбаев", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 29]		
        insert_application(apps, parameters)

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=17) + timedelta(minutes=random.randint(2, 360))
        parameters = [tel_id ,  get_telefon(), "Адина", "Сарсенбаева", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 29]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=16) + timedelta(minutes=random.randint(2, 360))
        parameters = [tel_id ,  get_telefon(), "Самат", "Манат", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 15]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=15) + timedelta(minutes=random.randint(2, 360))
        parameters = [tel_id ,  get_telefon(), "Мират", "Төлеуов", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 15]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=14) + timedelta(minutes=random.randint(2, 360))
        parameters = [tel_id ,  get_telefon(), "Диана", "Сырымбет", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 9]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=13) + timedelta(minutes=random.randint(2, 360))
        parameters = [tel_id ,  get_telefon(), "Гулзия", "Досанова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 9]		
        insert_application(apps, parameters)   

        # Пользователи Telegram заявки (там автоматом движение заявки)
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=12) + timedelta(minutes=random.randint(2, 360))
        parameters = [tel_id ,  get_telefon(), "Аскар", "Ахметов", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, 9]		
        insert_application(apps, parameters)   

        print("Пользователи + заявка ОК")

    except Exception as error:
        print(error)

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(new_data),
        migrations.RunSQL("""CREATE VIEW view_catalog AS
SELECT catalog.id, catalog.category_id, category.category_title AS category, catalog.catalog_title, catalog.details, catalog.price, catalog.photo
FROM catalog LEFT JOIN category ON catalog.category_id = category.id;
"""),
# SQLite
#        migrations.RunSQL("""CREATE VIEW view_application AS
#SELECT application.id, application.date_application, application.telegram_id, customer.phone_number, customer.first_name, customer.last_name, customer.date_joined, application.catalog_id, catalog.category_id, category.category_title AS category, catalog.catalog_title, catalog.details, catalog.price, catalog.photo,
#(SELECT strftime('%d.%m.%Y',datem) || ' - ' || status FROM movement WHERE application_id = application.id ORDER BY datem DESC LIMIT 1) AS final
#FROM application
#LEFT JOIN customer ON application.telegram_id=customer.telegram_id
#LEFT JOIN catalog ON application.catalog_id=catalog.id
#LEFT JOIN category ON catalog.category_id=category.id
#"""),
# PostgreSQL
        migrations.RunSQL("""CREATE VIEW view_application AS
SELECT application.id, application.date_application, application.telegram_id, customer.phone_number, customer.first_name, customer.last_name, customer.date_joined, application.catalog_id, catalog.category_id, category.category_title AS category, catalog.catalog_title, catalog.details, catalog.price, catalog.photo,
(SELECT  to_char(datem, 'DD.MM.YYYY') || ' - ' || status FROM movement WHERE application_id = application.id ORDER BY datem DESC LIMIT 1) AS final
FROM application
LEFT JOIN customer ON application.telegram_id=customer.telegram_id
LEFT JOIN catalog ON application.catalog_id=catalog.id
LEFT JOIN category ON catalog.category_id=category.id
"""),
    ]


